#服务端口号
server:
  port: 8001

#服务名称（服务注册到eureka名称）
spring:
  application:
    name: app-order
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
#注册到eureka
    register-with-eureka: true
#从eureka上获取注册信息
    fetch-registry: true

